### ISSUE TITLE
Parselog for tmux doesn't work as expected

### ISSUE THREAD

**Issue by nixpulvis** [jwilm/vte#13]
Running `tmux | target/debug/examples/parselog` always outputs simply the following:

```
[print] '['
[print] 'e'
[print] 'x'
[print] 'i'
[print] 't'
[print] 'e'
[print] 'd'
[print] ']'
[execute] 0a
```

All actions inside `tmux` are ignored. Maybe this is actually a expected behavior and I just don't understand how tmux interacts with the terminal.

**Comment by nixpulvis** [comment]
Hmmm, looks like STDIN's `read` call is never getting hit. So tmux doesn't use STDOUT in the same way as like every other program I've tried with?

P.S. I don't really know anything about tmux yet, sorry if this is all pretty obvious stuff.

**Comment by jwilm** [comment]
tmux is probably aware of whether it's running in a tty or not

**Comment by nixpulvis** [comment]
Right, sorry for all the noise. I'm trying to debug commands passed from tmux to alacritty, and this was where I started. Thoughts for a better approach?

**Comment by jwilm** [comment]
you can run alacritty -vvv and it will print out every control sequence it handles. It's kind of noisey, though.

**Comment by nixpulvis** [comment]
:sweat_smile:
