### ISSUE TITLE
hook method appears to be missing the final character

### ISSUE THREAD

**Issue by doy** [jwilm/vte#28]
my understanding is that the introducer for a device control string should follow the same syntax as a csi sequence, which means that the final character is used to determine the operation to perform. the `hook` method in the `Perform` trait doesn't receive the final byte though (like `csi_dispatch` does), so this doesn't appear to be possible.

(it's possible that i'm confused about something here - i don't really have a need for this, i just noticed it when trying to add some debug logs for the parsing process.)

**Comment by chrisduerr** [comment]
> my understanding is that the introducer for a device control string should follow the same syntax as a csi sequence

I'm not quite sure what you mean by this. Looking at the docs, it seems like the structure of CSIs and DCSs is quite different.

Are you saying that there's a missing `action` as parameter to the `hook` function?

**Comment by doy** [comment]
the final byte of the overall dcs should be a string terminator, but that is what triggers the `unhook` method (which correctly doesn't have a parameter). the final byte of the dcs introducer is the thing you need at `hook` time to determine which dcs sequence was given, and my understanding is that the dcs introducer has exactly the same structure as a csi sequence (except that it uses `ESC P` instead of `ESC [`). for instance, given something like `ESC P 5 g foobar ST`, `hook` is called after the `g`, then `put` is called for each byte in `foobar`, then `unhook` is called when `ST` is seen. the problem is that currently the value of `g` is lost, so there's no way to actually interpret the bytes given to `put`.

https://github.com/jwilm/vte/compare/master...doy:patch-1 is what i believe should be the correct behavior (don't have time to make a full pr at the moment, but i can clean it up in a bit if the idea looks reasonable).

**Comment by chrisduerr** [comment]
I'd have to look at the output myself and check the contents of `params` and `intermediates`. Though it would probably make sense to look at actual escapes, I don't think `ESC P 5 g foobar ST` would do anything, right? At least it's not mentioned in the XTerm docs.
